import Head from "next/head";
import { Header } from "@/components/Header";
import { DashBoard } from "@/components/DashBoard";

export default function Home() {
  return (
    <>
      <Head>
        <title>DUTCH0X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/DUTCH.svg" />
      </Head>
      <main className="p-0 m-0">
        <Header />
        <DashBoard />
      </main>
    </>
  );
}
